trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

stages:
    - stage: Build
      jobs:
          - job: 'BuildJob'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world'
    - stage: Test
      jobs:
          - job: 'TestJob'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Hello world'
    - stage: Deploy
      jobs:
          - job: 'DeployJob'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here                  
                  echo 'Prod Successful'
